---
Name: goldfinch-seo
---

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Goldfinch\Seo\Extensions\SiteConfigExtension

SilverStripe\CMS\Model\SiteTree:
  extensions:
    - Goldfinch\Seo\Extensions\SEOExtension

SilverStripe\Control\Director:
  rules:
    'humans.txt': 'Goldfinch\Seo\Humans'
    'manifest.webmanifest': 'Goldfinch\Seo\Webmanifest'
