---
Name: goldfinch-seo
---

SilverStripe\Core\Injector\Injector:
  Psr\SimpleCache\CacheInterface.MetaUniverse:
    factory: SilverStripe\Core\Cache\CacheFactory
    constructor:
      namespace: 'MetaUniverse'


Goldfinch\Seo\Models\OpenGraph:
  has_many:
    Pages: SilverStripe\CMS\Model\SiteTree

SilverStripe\CMS\Model\SiteTree:
  extensions:
    - Goldfinch\Seo\Extensions\SEOExtension
    - Goldfinch\Seo\Extensions\SchemaExtension
    - Goldfinch\Seo\Extensions\OpenGraphExtension
    - Goldfinch\Seo\Extensions\TwitterCardExtension

SilverStripe\Control\Director:
  rules:
    'humans.txt': 'Goldfinch\Seo\Humans'
    'manifest.webmanifest': 'Goldfinch\Seo\Webmanifest'
    'favicon.ico': 'Goldfinch\Seo\Favicon'
    'opensearch.xml': 'Goldfinch\Seo\Opensearch'

Goldfinch\Seo\Opensearch:
  opensearch:
    'enable': false
    'encoding': 'UTF-8'
    'title': ''
    'icoIcon': ''
    'searchURL': ''
    'suggestionURL': ''
    'searchForm': ''

PageController:
  extensions:
    - Goldfinch\Seo\Extensions\MetaUniverse

SilverStripe\Assets\File:
  allowed_extensions:
    - svg
    - ico

TractorCow\Robots\Robots:
  extensions:
    - Goldfinch\Seo\Extensions\RobotsExtension

SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - 'goldfinch/seo: styles/seo.css'
