---
Name: goldfinch-seo
---

SilverStripe\CMS\Model\SiteTree:
  extensions:
    - Goldfinch\Seo\Extensions\SEOExtension

SilverStripe\Control\Director:
  rules:
    'humans.txt': 'Goldfinch\Seo\Humans'
    'manifest.webmanifest': 'Goldfinch\Seo\Webmanifest'

PageController:
  extensions:
    - Goldfinch\Seo\Extensions\MetaUniverse

SilverStripe\Assets\File:
  allowed_extensions:
    - svg
    - ico

TractorCow\Robots\Robots:
  extensions:
    - Goldfinch\Seo\Extensions\RobotsExtension

SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - 'goldfinch/seo: styles/seo.css'
