---
Name: goldfinch-seo
---

SilverStripe\CMS\Model\SiteTree:
  extensions:
    - Goldfinch\Seo\Extensions\SEOExtension

SilverStripe\Control\Director:
  rules:
    'humans.txt': 'Goldfinch\Seo\Humans'
    'manifest.webmanifest': 'Goldfinch\Seo\Webmanifest'

PageController:
  extensions:
    - Goldfinch\Seo\Extensions\MetaUniverse
